spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: JasonJason
  session:
    store-type: none
server:
  port: 8060